function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(2)=((1-params(2)*(1-params(3)))/(params(2)*params(1)*exo_(1)))^(1/(params(1)-1));
    ys_(1)=exo_(1)*ys_(2)^params(1)-params(3)*ys_(2);
    % Auxiliary equations
ys_(3)=exo_(1);
end
